pipeline:

  build_image:
    image: quay.io/ukhomeofficedigital/centos-base:latest
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - yum install -y -q docker openssl wget
      - ./ci-build.sh
    when:
      event: [pull_request, push, tag]

  push_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - REPO="artifactory-internal.digital.homeoffice.gov.uk"
      - BASE="/"
      - NAME="nginx-proxy"
      - FULL_NAME="${REPO}${BASE}${NAME}"
      - DOCKER_USERNAME="lev-web-robot"
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${REPO}"
      - docker tag ngx "${FULL_NAME}:${DRONE_TAG}"
      - docker tag ngx "${FULL_NAME}:latest"
      - docker push "${FULL_NAME}:${DRONE_TAG}"
      - docker push "${FULL_NAME}:latest"
    when:
      event: tag

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
