workspace:
  base: /workdir

pipeline:
  # build_and_test_image:
  #   image: docker:17.12.0 # not sure why it needed to use a centos base image
  #   environment:
  #     - DOCKER_HOST=tcp://172.17.0.1:2375
  #   commands:
  #     - apk update
  #     - apk add bash curl openssl wget
  #     - ./ci-build.sh
  #   when:
  #     event: [pull_request, push, tag]

  build_and_test_image:
    image: quay.io/ukhomeofficedigital/centos-base:v0.5.7 # testing with a centos image
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - yum update -y
      - yum install -y -q docker openssl wget
      - ./ci-build.sh
    when:
      event: [pull_request, push, tag]

  push_image_to_artifactory:
    image: docker:17.12.0
    secrets:
      - docker_password # to be added
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=artifactory-internal.digital.homeoffice.gov.uk
      - DOCKER_BASEDIR=/
      - DOCKER_USERNAME=lev-web-robot
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag

  push_image_to_quay:
    image: docker:17.12.0
    secrets:
      - docker_quay_password # to be added
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_USERNAME=ukhomeofficedigital+nginx_proxy
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_QUAY_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag
